GuildAutomotive/GuildAutomotive/Controllers/InventoryController.cs
using GuildAuto.Data.Factory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildAutomotive.Controllers
{
    public class InventoryController : Controller
    {
        // GET: NewInventory
        public ActionResult New()
        {
            return View();
        }

        //GET : UsedInventory
        public ActionResult Used()
        {
            return View();
        }

        //GET : Details
        public ActionResult Details(int id)
        {
            var model = ListingRepositoryFactory.GetRepository().GetVehicleById(id);
            return View(model);
        }

       
    }
}

GuildAutomotive/GuildAutomotive/Controllers/ReportsController.cs
using GuildAuto.Data.Factory;
using GuildAuto.Models.Queries;
using GuildAutomotive.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildAutomotive.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Reports
        [Authorize(Roles ="admin")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Sales()
        {
            var model = new SalesReportViewModel();
            var repo = ReportsRepositoryFactory.GetRepository();
            var adminRepo = AdminUserRepositoryFactory.GetRepository();

            model.Sales = repo.GetAllSales();
            model.Parameters = new SalesSearchParameters();
            model.AdminUser = new SelectList((from s in adminRepo.GetAllUserDetails()
                                              select new
                                              {
                                                  Id = s.Id,
                                                  FullName = s.FirstName + ' ' + s.LastName
                                              }), "Id", "FullName");

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Inventory()
        {
            var model = new InventoryReportViewModel();
            var repo = ReportsRepositoryFactory.GetRepository();

            model.NewInventory = repo.GetNewInventory();
            model.UsedInventory = repo.GetUsedInvetory();

            return View(model);
        }
    }
}

GuildAutomotive/GuildAutomotive/Controllers/SalesController.cs
using GuildAuto.Data.Factory;
using GuildAuto.Models.Queries;
using GuildAuto.Models.Tables;
using GuildAutomotive.Models;
using GuildAutomotive.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildAutomotive.Controllers
{
    public class SalesController : Controller
    {
        // GET: Sales
        [Authorize(Roles = "sales, admin")]
        public ActionResult Index()
        {
            var model = ListingRepositoryFactory.GetRepository().GetAllVehicles();
            return View(model);
        }

        [Authorize(Roles = "sales, admin")]
        public ActionResult Purchase(int id)
        {
            var model = new PurchaseViewModel();

            var statesRepo = StatesRepositoryFactory.GetRepository();
            var listingRepo = ListingRepositoryFactory.GetRepository();
            var purchaseRepo = PurchaseTypesRepositoryFactory.GetRepository();



            model.States = new SelectList(statesRepo.GetAllStates(), "StateId", "StateName");
            model.ListingItem = listingRepo.GetVehicleById(id);
            model.PurchaseTypes = new SelectList(purchaseRepo.GetAllPurchaseTypes(), "PurchaseTypeId", "PurchaseType");
            model.PurchaseInfo = new PurchaseInfo();

            model.ListingItem.VehicleId = id;

            return View(model);
        }

        [Authorize(Roles = "sales, admin")]
        [HttpPost]
        public ActionResult Purchase(PurchaseViewModel model)
        {
            model.PurchaseInfo.PurchaseDate = DateTime.Now;
            model.PurchaseInfo.Id = "1";
            model.PurchaseInfo.VehicleId = model.ListingItem.VehicleId;

            var sold = new SoldVehicle();

            sold.VehicleId = model.ListingItem.VehicleId;
            sold.Sold = true;
            sold.ImageFileName = "sold.jpg";
            sold.Featured = false;

            if (ModelState.IsValid)
            {
                var repo = PurchaseInfoRepositoryFactory.GetRepository();

                try
                {
                    model.PurchaseInfo.Id = AuthorizeUtilities.GetUserId(this);

                    repo.InsertPurchase(model.PurchaseInfo);

                    repo.UpdateSold(sold);

                    return RedirectToAction("Index", "Sales");
                }

                catch (Exception ex)
                {
                    throw ex;
                }
            }

            else
            {
                var statesRepo = StatesRepositoryFactory.GetRepository();
                var listingRepo = ListingRepositoryFactory.GetRepository();
                var purchaseRepo = PurchaseTypesRepositoryFactory.GetRepository();

                model.States = new SelectList(statesRepo.GetAllStates(), "StateId", "StateName");
                model.ListingItem = listingRepo.GetVehicleById(model.PurchaseInfo.VehicleId);
                model.PurchaseTypes = new SelectList(purchaseRepo.GetAllPurchaseTypes(), "PurchaseTypeId", "PurchaseType");
                model.PurchaseInfo = new PurchaseInfo();

                return View(model);
            }
        }
    }
}

GuildAutomotive/GuildAutomotive/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div>
        <h4><strong>Reports</strong></h4>
    </div>
    <br />
    <div class="row">
        @Html.ActionLink("Inventory Report", "Inventory", "Reports")
    </div>
    <br />
    <div class="row">
        @Html.ActionLink("Sales Report", "Sales", "Reports")
    </div>
</div>

GuildAutomotive/GuildAutomotive/Views/Reports/Inventory.cshtml
@model GuildAutomotive.Models.InventoryReportViewModel
    @{
        ViewBag.Title = "Inventory";
    }
    <div class="container col-lg-6 col-sm-12">
        <h4><strong>Inventory Report</strong></h4>
        <br />
        <h5><strong>New Vehicles</strong></h5>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Count</th>
                    <th>Stock Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var car in Model.NewInventory)
                {
                    <tr>
                        <td>@car.ModelYear</td>
                        <td>@car.Make</td>
                        <td>@car.CarModel</td>
                        <td>@car.Stock</td>
                        <td>$@car.StockValue</td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        <h5><strong>Used Vehicles</strong></h5>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Count</th>
                    <th>Stock Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var car in Model.UsedInventory)
                {
                    <tr>
                        <td>@car.ModelYear</td>
                        <td>@car.Make</td>
                        <td>@car.CarModel</td>
                        <td>@car.Stock</td>
                        <td>$@car.StockValue</td>
                    </tr>
                }
            </tbody>
        </table>


    </div>

GuildAutomotive/GuildAutomotive/Views/Reports/Sales.cshtml
@model GuildAutomotive.Models.SalesReportViewModel

@{
    ViewBag.Title = "Sales";
}


<div class="container">
    <h4><strong>Sales</strong></h4>
    <div class="row">
        <div class="col-lg-7 col-xs-12">
            <div class="well">
                <form id="salesFilters" class="form-inline">
                    <div class="row">
                        <h5><strong>Filters</strong></h5>
                    </div>
                    <div class="row form-group-sm">
                        <div class="form-group">
                            <label for="User">User</label>
                            @Html.DropDownListFor(m => m.AdminUser, Model.AdminUser, "ALL", new { @class = "form-control", id = "userId" })
                        </div>
                        <div class="form-group">
                            <label for="fromDate">From Date</label>
                            <input class="form-control" id="fromDate" type="datetime">
                        </div>
                        <div class="form-group">
                            <label for="toDate">To Date</label>
                            <input class="form-control" id="toDate" type="datetime">
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <button id="btnSearch" class="btn btn-default btn-sm col-lg-3">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="col-lg-6 col-xs-12">
        <h5><strong>Search Results</strong></h5>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Total Sales</th>
                    <th>Total Vehicles</th>
                </tr>
            </thead>
            <tbody id="searchResults">
                @foreach (var admin in Model.Sales)
            {
                    <tr>
                        <td>@admin.User</td>
                        <td>$@admin.TotalSales</td>
                        <td>@admin.NumberOfSales</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#salesFilters").submit(function (e) {
                search();
                return false;
            });
        });

        function search() {
            var params;


            params = 'userId=' + $('#userId').val() + '&' + 'fromDate=' + $('#fromDate').val() + '&' + 'toDate=' + $('#toDate').val();

            $.ajax({
                type: 'Get',
                url: 'http://localhost:51913/api/reports/sales?' + params,
                success: function (results) {
                    $('#searchResults').empty();

                    $.each(results, function (index, sale) {
                        var html = '<tr><td>' + sale.User + '</td><td>$' + sale.TotalSales + '.00</td><td>' + sale.NumberOfSales + '</td></tr>';

                        $('#searchResults').append(html.toString());
                    });
                },
                error: function () {
                    alert: ('error')
                }


            });
        }
    </script>


}